### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by matteos1** [pinkywafer/Anniversaries#167] opened 2024-10-03 17:52 UTC
In ha 2024.10.0 not work

**Comment by ChirpyTurnip** [comment] 2024-10-03 18:00
Duplicate of #165. Please marked as closed.

**Comment by stavyamm** [comment] 2024-10-06 10:08
In ha 2024.10.0 not work

**Comment by BebeMischa** [comment] 2024-10-06 10:56
So go and see #165

**Comment by pinkywafer** [comment] 2024-10-14 13:01
duplicate of #165

**Closed by pinkywafer** 2024-10-14 13:01 UTC
