### ISSUE TITLE
In correct year calculation

### ISSUE THREAD

**Issue by NicolaiVdS** [pinkywafer/Anniversaries#3] opened 2019-11-05 06:52 UTC
I have added my own birthday and it came up that I'm 26 but I am actually 25

**Comment by pinkywafer** [comment] 2019-11-05 07:14
The years attribute was intended to be the age at the next occurrence,  i.e. in {state} days, {name} will be {years} old. 
If anyone is using it for this,  changing this would cause disruption,  so it may be better to add a 'current years' attribute as well?
It may actually be a better idea to rename the years attribute to 'years at next occurrence'.

**Comment by NicolaiVdS** [comment] 2019-11-05 09:05
@pinkywafer yes that would make sense yeah
Also might update the readme since it's not correct

**Comment by pinkywafer** [comment] 2019-11-05 10:24
Closed in New release v 0.3.0

**Closed by pinkywafer** 2019-11-05 10:24 UTC

**Comment by NicolaiVdS** [comment] 2019-11-05 10:52
not to be an ass but the 0.3.0 release has the same atribs as the 0.2.0

**Comment by pinkywafer** [comment] 2019-11-05 11:24
Apologies...   I missed a merge... hate working on mobile! 
Try 0.3.1
