### ISSUE TITLE
Feature Request: Frequency for Monthly Anniversaries

### ISSUE THREAD

**Issue by woodmj74** [pinkywafer/Anniversaries#118] opened 2022-01-27 10:18 UTC
Firstly, thank you Hassio Queen for the work you have done here, I moved to this from a script-based solution because it felt better and proved to be!

I’d like to propose a possible enhancement for consideration. Prior to moving to this solution I’d created the option to have a frequency for the anniversary. I know the primary use case here is around birthdays or other such annual events but I found it useful to have sensors around monthly events (for example Credit Card monthly payment).

Whilst I don’t want to solutionize for you I saw this a possible new Configuration Parameter, perhaps `frequency`. When not defined, it would default to annual but you could also define monthly. All other options I think would still be valid (`count_up`, `date_template `etc.). 
If I had a sensor configured as:

```
name: Amex
date: 2022/01/15
frequency: monthly
id_prefix: Credit_Card
```

Within HA (assuming today is 2022/01/27) my sensor would look like:

```
entity_id: sensor.credit_card_amex
state: 19 
attribution: Sensor data calculated by Anniversaries Integration
years_at_next_anniversary: 1
current_years: 0
date: '2022-01-15T00:00:00+01:00'
frequency: monthly
weeks_remaining: 2
unit_of_measurement: Days
icon: mdi:calendar-blank
friendly_name: Amex
```

If we then pretend the date is 2023/04/17, the sensor will look like this:

```
entity_id: sensor.credit_card_amex
state: 28 
attribution: Sensor data calculated by Anniversaries Integration
years_at_next_anniversary: 2
current_years: 1
date: '2022-01-15T00:00:00+01:00'
frequency: monthly
weeks_remaining: 4
unit_of_measurement: Days
icon: mdi:calendar-blank
friendly_name: Amex
```

You could also then consider frequencies of bi-monthly, half-yearly (alongside the half anniversary feature). 

I hope this is of interest, happy to assist with any thoughts (but my code is shocking). Once again thank you for this, I love it (and your vid’s on Browser Mod were very helpful!!!)

**Comment by pinkywafer** [comment] 2023-02-16 18:19
duplicate of #58

**Closed by pinkywafer** 2023-02-16 18:19 UTC
Labels: enhancement, undecided
